var $fpdChapas=$('#fpd-chapas'),
    pluginOpts = {
    //editorMode: true,
    stageHeight: 700,
    width:700,
    hideDialogOnAdd:true,
    customImageParameters: {
        colors: false,
        autoCenter: true,
        removable: true,
        maxH:7000,
        maxW:7000,
        minH:100,
        minW:100,
        resizeToH:635,
        resizeToW:635,
        resizable:false,
        draggable:false,
        opacity:1,
        boundingBox: "Bounding",
        z:1,
    },
    elementParameters:{
        draggable:false,
        removable:false,
        autoCenter:true,
        resizable:false,
        rotatable:false,
        opacity:1,
    },
    mainBarModules: ['images', 'designs'],
    langJSON: '/vendor/fancy_product_designer/source/lang/es.json',
    templatesDirectory: '/vendor/fancy_product_designer/source/html/'
},
fpdChapas = new FancyProductDesigner($fpdChapas, pluginOpts);
