var $fpdLienzos=$('#fpd-lienzos'),
        pluginOpts = {
        //editorMode: true,
        stageHeight: 700,
        width:700,
        hideDialogOnAdd:true,
        customImageParameters: {
            colors: false,
            autoCenter: true,
            removable: true,
            maxH:7000,
            maxW:7000,
            minH:400,
            minW:400,
            resizeToH:485,
            resizeToW:485,
            resizable:true,
            draggable:false,
            opacity:1,
            boundingBox: "Bounding",
            boundingBoxMode: "limitModify",
            z:1,
        },
        elementParameters:{
            draggable:false,
            removable:false,
            resizable:false,
            rotatable:false,
            opacity:1,
        },
        mainBarModules: ['products','images'],
        langJSON: '/vendor/fancy_product_designer/source/lang/es.json',
        templatesDirectory: '/vendor/fancy_product_designer/source/html/'
    },
    fpdLienzos = new FancyProductDesigner($fpdLienzos, pluginOpts);
