    var $fpd=$('#fpd'),
        pluginOpts = {
        //editorMode: true,
        stageHeight: 700,
        width:700,
        hideDialogOnAdd:true,
        customImageParameters: {
            colors: false,
            autoCenter: true,
            removable: true,
            maxH:7000,
            maxW:7000,
            minH:300,
            minW:300,
            resizeToH:500,
            resizeToW:500,
            resizable:false,
            draggable:false,
            boundingBox: "Bounding",
            boundingBoxMode: "limitModify",
            z:1,
        },
        elementParameters:{
            draggable:false,
            removable:false,
            autoCenter:true,
            resizable:false,
            rotatable:false,
        },
        mainBarModules: ['products','images'],
        langJSON: '/vendor/fancy_product_designer/source/lang/es.json',
        templatesDirectory: '/vendor/fancy_product_designer/source/html/'
    },
    fpd = new FancyProductDesigner($fpd, pluginOpts);
