var $fpd=$('#fpd'),
    pluginOpts = {
    //editorMode:true,
    stageHeight: 700,
    width:700,
    hideDialogOnAdd:true,
    customImageParameters: {
        autoCenter: true,
        removable: true,
        maxH:10000,
        maxW:10000,
        minH:400,
        minW:230,
        resizeToW:225,
        resizable:true,
        draggable:true,
        boundingBox: "Bounding",
        boundingBoxMode: "clipping",
        copyable:false,
        z:3,
        //uploadZoneScaleMode:"cover",
    },
    elementParameters:{
        draggable:false,
        removable:false,
        resizable:false,
        rotatable:false,
        customTexts:false,
    },
    mainBarModules: ['products','images'],
    langJSON: '/vendor/fancy_product_designer/source/lang/es.json',
    templatesDirectory: '/vendor/fancy_product_designer/source/html/'
},
fpd = new FancyProductDesigner($fpd, pluginOpts);
